before_install:
  - chmod +x mvnw
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('123456') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
language: java
jdk:
  - oraclejdk8